### ISSUE TITLE
matching throws error when no matches are found

### ISSUE THREAD

**Issue by paolap** [coecms/clef#129]
Error is

Traceback (most recent call last):
  File "prova_clef.py", line 9, in <module>
    results, selection = matching(s, allvalues, fixed, project='CMIP6', **constraints)
  File "/home/581/pxp581/clef/clef/code.py", line 122, in matching
    return and_filter(results, cols, fixed, **kwargs)
  File "/home/581/pxp581/clef/clef/code.py", line 297, in and_filter
    fullrow = df[df.index.isin(selection['index'].sum())]
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 4667, in isin
    return algos.isin(self, values)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/site-packages/pandas/core/algorithms.py", line 411, in isin
    "only list-like objects are allowed to be passed "
TypeError: only list-like objects are allowed to be passed to isin(), you passed a [int]

caused by trying to index the results using selection index when its length is zero
code.py line: 295

    fullrow = df[df.index.isin(selection['index'].sum())]

Easily fixed by: 
 if len(selection.index) > 0 :
        fullrow = df[df.index.isin(selection['index'].sum())]
    else:
        fullrow = pd.DataFrame(columns=df.columns)

**Comment by paolap** [comment]
This is fixed in release 1.2
