### ISSUE TITLE
clef cmip6 produces error while searching CMIP6 queued table

### ISSUE THREAD

**Issue by paolap** [coecms/clef#61]
clef cmip6 -e 1pctCO2 --activity CMIP -t Amon -v tas          
Traceback (most recent call last):
  File "/g/data3/hh5/public/apps/miniconda3/envs/clef-test/bin/clef", line 11, in <module>
    sys.exit(clef())
  File "/g/data3/hh5/public/apps/miniconda3/envs/clef-test/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/g/data3/hh5/public/apps/miniconda3/envs/clef-test/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/g/data3/hh5/public/apps/miniconda3/envs/clef-test/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/g/data3/hh5/public/apps/miniconda3/envs/clef-test/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/g/data3/hh5/public/apps/miniconda3/envs/clef-test/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/g/data3/hh5/public/apps/miniconda3/envs/clef-test/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/g/data3/hh5/public/apps/miniconda3/envs/clef-test/lib/python3.7/site-packages/clef/cli.py", line 432, in cmip6
    updated = search_queue_csv(qm, project, [])
  File "/g/data3/hh5/public/apps/miniconda3/envs/clef-test/lib/python3.7/site-packages/clef/download.py", line 83, in search_queue_csv
    rows[row[1]] = [row[0],row[2]]
IndexError: list index out of range

This error is caused by the fact the CMIP6_clef_table.csv has one less field then the corresponding CMIP5 table.
It's fixed in the latest "collections" commit

**Comment by ScottWales** [comment]
Appears to be due to a change in MAS. The selector to find CMIP6 data files returns no matches
```
postgres=> select count(*) from oi10.paths where pa_type in ('file', 'link') and pa_parents[4] = md5('/g/data1b/oi10/replicas')::uuid;
 count 
-------
     0
```
The `pa_parents[4]` check is supposed to find paths starting with that prefix

The files are actually present if we do an explicit search
```
postgres=> select count(*) from oi10.paths where pa_type in ('file', 'link') and pa_path like '/g/data1b/oi10/replicas/%';
 count 
-------
  4235
```

**Comment by paolap** [comment]
This is now solved and in the latest release

**Comment by paolap** [comment]
I'm re-opening this because it looks like this is till happening or potentially this fix has broken the functionality again. It is not producing an error currently but it's skipping the check. I've fixed it in the branch 'notebook' on which i'm working updating the demo.

**Comment by paolap** [comment]
Merged to master closing this issue
