### ISSUE TITLE
Bug in request mode 

### ISSUE THREAD

**Issue by DamienIrving** [coecms/clef#84]
I'm using clef version 0.5.0 installed via `conda install -c coecms -c conda-forge clef`.

This is a minor issue, but when I used the request mode I got the following error. It looks like the request was successfully submitted, but right at the end an error occurred when it tried to print some information to the screen. 

```
$ clef --request cmip5 --experiment piControl --latest --variable wfcorr --variable wfonocorr --variable vsf --variable vsfcorr --variable zostoga --variable zosga --variable zossga --table Omon --ensemble r1i1p1

...

Finished writing file: CMIP5_dbi599_20190808T145542.txt
Do you want to proceed with request for missing files? (N/Y)
 No is default
Y
Your request was successfully sent to the NCI helpdesk
Traceback (most recent call last):
  File "/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/clef/download.py", line 73, in helpdesk
    print(f'A copy of your request has been saved in \n {current_dir}/{fname}')
NameError: name 'current_dir' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/g/data/r87/dbi599/miniconda3/envs/ocean/bin/clef", line 10, in <module>
    sys.exit(clef())
  File "/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/clef/cli.py", line 350, in cmip5
    write_request('CMIP5',updated)
  File "/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/clef/download.py", line 48, in write_request
    helpdesk(user, current_dir, fname, project)
  File "/g/data/r87/dbi599/miniconda3/envs/ocean/lib/python3.6/site-packages/clef/download.py", line 74, in helpdesk
    except SMTPException:
NameError: name 'SMTPException' is not defined
```

**Comment by ScottWales** [comment]
Thanks Damien, I see what's happened, will put together a fix

**Comment by DamienIrving** [comment]
Thanks, @ScottWales.
